### ISSUE TITLE
Copper and Lead Acid Battery blueprints NOT SHOWING in Fabricator on acid mushroom pickup

### ISSUE THREAD

**Issue by FunkyToc** [tinyhoot/Deathrun-Remade#14]
Copper and Lead Acid Battery blueprints are not visible in the fabricator, after picking acid mushrooms (or other trigger).
This can be fixed ingame by closing the game client and starting it again (reloading blueprints?).
Saving, going back to the main menu and lauching the save do not fix it.

Living Large update march-2023 71288
Using Vortex install.

**Comment by Mar-Veloz** [comment]
This also happens with the Integrated air filter and upgraded dive suit recipes, so I don't think it's an issue unique to just the battery blueprints.

**Comment by tinyhoot** [comment]
The bug is caused by loading into a game and quitting back out without interacting with a fabricator. From that point on all recipes associated with that type of craft tree will be missing. It's a byproduct of three things: `CraftTree` being static and not unloading properly from game to game, the way Nautilus' patchers queue up changes, and Nautilus only patching when a CraftTree is first requested.

I've created a surface level patch for this that forces craft trees to get cached every game, but ultimately a proper fix will have to come from Nautilus' side. For now, this patch should hide the issue from players.
