### ISSUE TITLE
Remove choking noise when holding an air bladder

### ISSUE THREAD

**Issue by Lewis-Bright** [tinyhoot/Deathrun-Remade#16]
A tactic to travel with limited air is to swim near the surface with an air bladder and use the air bladder to filter air, then dive beneath the surface to take a breath. This leads to constantly triggering the choking sound effect when you resurface to refill the bladder, which is an annoying sound.

My suggestion is to just remove the choking sound (but not the warning notification) when you surface holding a bladder. The player probably doesn't need to be reminded that they can't breathe because they are surfacing purposefully to fill the air bladder (also it would be a bit weird thematically if Riley kept trying to breathe when doing this...) I've made this change locally and tested it and it works quite well. I am happy to submit a PR if this seems like a good idea.

A potential follow-up would be to allow breathing through the air bladder whilst at the surface. Either by allowing the player to breathe normally while holding it, or to modify the item behaviour so it can be used whilst at the surface (similar problem to the air pump).

**Comment by tinyhoot** [comment]
The air bladder filling up despite the poisonous atmosphere was an oversight. https://github.com/tinyhoot/Deathrun-Remade/commit/fb38e63ef2c5e3c6f16ac8c6da3757c0af88dda1 fixes this. Since there is now no longer a situation where one would keep dolphin diving along the surface with an air bladder, I do not think it is necessary to remove the choking noise.
