### ISSUE TITLE
Island food not grabbable/edible even after Aurora fixed

### ISSUE THREAD

**Issue by Xunnamius** [tinyhoot/Deathrun-Remade#4]
Hi there, thanks for this fun remake. I have the "Challenge: Island Food" setting at "Edible after fixing reactor," which I fixed maybe 150-200 days in. I'm on day 254 and I can't interact with any of the island food at all. When cutting them with a knife, I don't get any seeds either. Is this intended behavior?

**Comment by tinyhoot** [comment]
Island food only becomes interactable after all trace of radiation has dissipated from the world, which can take a few days after you fix the reactor. That does not sound like it's the problem here given that you fixed it a long time ago. I'll take a look.
Either way it's probably worth adding a new interaction message for the plants after the reactor has been fixed that roughly explains why the plants still aren't harvestable.
